kind: ConfigMap
apiVersion: v1
metadata:
  name: wg-configmap
data:
  wg0.conf: |
    [Interface]
    PrivateKey = <the private key>
    Address = 10.33.0.1/24
    ListenPort = 5555

    [Peer]
    PublicKey = YqbrhFUwJpO1MriIFcwJMaBs5HwwQa0sPebGyOafahQ=
    AllowedIPs = 10.33.0.2/32

    [Peer]
    PublicKey = e6jSxfQPJJsTOzRM7KIPt7IUr2XX/TV+C+PqQX8hL28=
    AllowedIPs = 10.33.0.3/32
---
kind: Service
apiVersion: v1
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  type: LoadBalancer
  ports:
    - name: wg
      protocol: UDP
      port: 5555
      targetPort: 5555
  selector:
    app: wireguard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: ellzap2/my-wireguard:latest
          ports:
            - containerPort: 5555
              protocol: UDP
              name: wireguard
          env:
            - name: LOG_LEVEL
              value: info
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          resources:
            requests:
              memory: 64Mi
              cpu: "100m"
            limits:
              memory: 256Mi
          volumeMounts:
            - name: cfgmap
              mountPath: /etc/wireguard/wg0.conf
              subPath: wg0.conf
      volumes:
        - name: cfgmap
          configMap:
            name: wg-configmap